# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(969, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.outputClonotypes = QtGui.QTextEdit(self.centralwidget)
        self.outputClonotypes.setGeometry(QtCore.QRect(30, 230, 581, 301))
        self.outputClonotypes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.outputClonotypes.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.outputClonotypes.setLineWrapColumnOrWidth(0)
        self.outputClonotypes.setReadOnly(True)
        self.outputClonotypes.setAcceptRichText(False)
        self.outputClonotypes.setObjectName(_fromUtf8("outputClonotypes"))
        self.motifEntry = QtGui.QLineEdit(self.centralwidget)
        self.motifEntry.setGeometry(QtCore.QRect(30, 50, 201, 27))
        self.motifEntry.setObjectName(_fromUtf8("motifEntry"))
        self.genesOutput = QtGui.QTextEdit(self.centralwidget)
        self.genesOutput.setGeometry(QtCore.QRect(650, 230, 251, 301))
        self.genesOutput.setReadOnly(True)
        self.genesOutput.setObjectName(_fromUtf8("genesOutput"))
        self.genesOutput.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.goButton = QtGui.QPushButton(self.centralwidget)
        self.goButton.setGeometry(QtCore.QRect(380, 100, 99, 27))
        self.goButton.setAutoFillBackground(False)
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 41, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 200, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 200, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cdrLengthEntry = QtGui.QLineEdit(self.centralwidget)
        self.cdrLengthEntry.setGeometry(QtCore.QRect(370, 50, 51, 27))
        self.cdrLengthEntry.setObjectName(_fromUtf8("cdrLengthEntry"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 130, 891, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 141, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.typeBox = QtGui.QComboBox(self.centralwidget)
        self.typeBox.setGeometry(QtCore.QRect(760, 50, 151, 27))
        self.typeBox.setObjectName(_fromUtf8("typeBox"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(770, 20, 68, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sampleEdit = QtGui.QLineEdit(self.centralwidget)
        self.sampleEdit.setGeometry(QtCore.QRect(500, 50, 101, 27))
        self.sampleEdit.setObjectName(_fromUtf8("sampleEdit"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(500, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.visitBox = QtGui.QComboBox(self.centralwidget)
        self.visitBox.setGeometry(QtCore.QRect(620, 50, 101, 27))
        self.visitBox.setObjectName(_fromUtf8("visitBox"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 20, 68, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.epitopeEdit = QtGui.QLineEdit(self.centralwidget)
        self.epitopeEdit.setGeometry(QtCore.QRect(260, 50, 71, 27))
        self.epitopeEdit.setObjectName(_fromUtf8("epitopeEdit"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 20, 68, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.loadData = QtGui.QAction(MainWindow)
        self.loadData.setObjectName(_fromUtf8("loadData"))
        self.toolBar.addAction(self.loadData)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Motif Search", None))
        self.goButton.setText(_translate("MainWindow", "Go!", None))
        self.label.setText(_translate("MainWindow", "Motif", None))
        self.label_2.setText(_translate("MainWindow", "CDR3 Length", None))
        self.label_3.setText(_translate("MainWindow", "Matching Sequences", None))
        self.label_4.setText(_translate("MainWindow", "Gene Families and Usage", None))
        self.label_5.setText(_translate("MainWindow", "RESULTS", None))
        self.label_7.setText(_translate("MainWindow", "Type", None))
        self.label_8.setText(_translate("MainWindow", "Sample", None))
        self.label_9.setText(_translate("MainWindow", "Visit", None))
        self.label_6.setText(_translate("MainWindow", "Epitope", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.loadData.setText(_translate("MainWindow", "Load Data", None))

